# Generated by Django 3.1.2 on 2020-12-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20201213_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='hours',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='week',
            field=models.PositiveIntegerField(),
        ),
    ]
