# Generated by Django 3.1.2 on 2020-12-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20201215_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='const',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
