# Generated by Django 3.1.2 on 2020-12-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_task_const'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrivalnote',
            name='pdf',
            field=models.FileField(upload_to='media/arrivalPDF/'),
        ),
    ]
